# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtWidgets, QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/white Icons/video.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{\n"
"background-color:rgb(0, 13, 20);\n"
"}\n"
"\n"
"QPushButton{\n"
"background: transparent;\n"
"text-align: center;\n"
"font: 75 15pt \"Comic Sans MS\";\n"
"color:  rgb(58, 180, 204);\n"
"border-radius: 30px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setStyleSheet("background-image: url(:/imgs/photo-1516450360452-9312f5e86fc7.jpg)")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_2.setMouseTracking(False)
        self.horizontalSlider_2.setTabletTracking(False)
        self.horizontalSlider_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider_2.setAcceptDrops(False)
        self.horizontalSlider_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_2.setAutoFillBackground(False)
        self.horizontalSlider_2.setStyleSheet("background: transparent;\n"
"-webkit-appearance:round;\n"
"border-radius: 5px;\n"
"color:  rgb(0, 255, 204);\n"
"")
        self.horizontalSlider_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setProperty("value", 0)
        self.horizontalSlider_2.setSliderPosition(0)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QPushButoon{\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.volume = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.volume.setFont(font)
        self.volume.setStyleSheet("#volume:hover{\n"
"icon: url(:/buttons/cyan icons/volume-down.svg)\n"
"}")
        self.volume.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/white Icons/volume-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volume.setIcon(icon1)
        self.volume.setIconSize(QtCore.QSize(35, 35))
        self.volume.setFlat(False)
        self.volume.setObjectName("volume")
        self.horizontalLayout_6.addWidget(self.volume)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMaximum(26)
        self.horizontalSlider.setPageStep(6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_6.addWidget(self.horizontalSlider)
        self.prev = QtWidgets.QPushButton(self.frame_2)
        self.prev.setStyleSheet("#prev:hover{\n"
"icon: url(:/buttons/cyan icons/previous.svg);\n"
"}")
        self.prev.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/white Icons/previous (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon2)
        self.prev.setIconSize(QtCore.QSize(35, 35))
        self.prev.setObjectName("prev")
        self.horizontalLayout_6.addWidget(self.prev)
        self.play = QtWidgets.QPushButton(self.frame_2)
        self.play.setToolTip("")
        self.play.setStyleSheet("border-radius: 38px;")
        self.play.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/cyan icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon3)
        self.play.setIconSize(QtCore.QSize(70, 70))
        self.play.setObjectName("play")
        self.horizontalLayout_6.addWidget(self.play)
        self.next = QtWidgets.QPushButton(self.frame_2)
        self.next.setStyleSheet("#next:hover{\n"
"icon: url(:/buttons/cyan icons/next (1).svg);\n"
"}")
        self.next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttons/white Icons/next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon4)
        self.next.setIconSize(QtCore.QSize(35, 35))
        self.next.setObjectName("next")
        self.horizontalLayout_6.addWidget(self.next)
        self.repeat = QtWidgets.QPushButton(self.frame_2)
        self.repeat.setWhatsThis("")
        self.repeat.setAccessibleName("")
        self.repeat.setAccessibleDescription("")
        self.repeat.setStyleSheet("#repeat{\n"
"border-radius: 10px;\n"
"}\n"
"#repeat:hover{\n"
"icon: url(:/buttons/cyan icons/repeat (1).svg);\n"
"}")
        self.repeat.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttons/white Icons/repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.repeat.setIcon(icon5)
        self.repeat.setIconSize(QtCore.QSize(35, 35))
        self.repeat.setObjectName("repeat")
        self.horizontalLayout_6.addWidget(self.repeat)
        self.playlist = QtWidgets.QPushButton(self.frame_2)
        self.playlist.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/imgs/cyan icons/playlist.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playlist.setIcon(icon6)
        self.playlist.setIconSize(QtCore.QSize(40, 40))
        self.playlist.setObjectName("playlist")
        self.horizontalLayout_6.addWidget(self.playlist)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Player"))
        self.volume.setToolTip(_translate("MainWindow", "volume"))
        self.volume.setShortcut(_translate("MainWindow", "P"))
        self.prev.setToolTip(_translate("MainWindow", "previous"))
        self.prev.setShortcut(_translate("MainWindow", "P"))
        self.play.setShortcut(_translate("MainWindow", "Space"))
        self.next.setToolTip(_translate("MainWindow", "next"))
        self.next.setShortcut(_translate("MainWindow", "N"))
        self.repeat.setToolTip(_translate("MainWindow", "repeat"))
        self.repeat.setShortcut(_translate("MainWindow", "R"))
        self.playlist.setToolTip(_translate("MainWindow", "playlist"))
        self.playlist.setShortcut(_translate("MainWindow", "P"))
import sources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
